// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.17.3
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]
//! Generated file from `samples.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:samples.Sample)
pub struct Sample {
    // message fields
    // @@protoc_insertion_point(field:samples.Sample.cfdna_yield)
    pub cfdna_yield: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:samples.Sample.albumin)
    pub albumin: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:samples.Sample.ldh)
    pub ldh: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:samples.Sample.alp)
    pub alp: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:samples.Sample.psa)
    pub psa: ::std::option::Option<f64>,
    // @@protoc_insertion_point(field:samples.Sample.liver_mets)
    pub liver_mets: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:samples.Sample.lung_mets)
    pub lung_mets: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:samples.Sample.ecog)
    pub ecog: ::std::option::Option<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:samples.Sample.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Sample {
    fn default() -> &'a Sample {
        <Sample as ::protobuf::Message>::default_instance()
    }
}

impl Sample {
    pub fn new() -> Sample {
        ::std::default::Default::default()
    }

    // optional double cfdna_yield = 1;

    pub fn cfdna_yield(&self) -> f64 {
        self.cfdna_yield.unwrap_or(-1.0f64)
    }

    pub fn clear_cfdna_yield(&mut self) {
        self.cfdna_yield = ::std::option::Option::None;
    }

    pub fn has_cfdna_yield(&self) -> bool {
        self.cfdna_yield.is_some()
    }

    // Param is passed by value, moved
    pub fn set_cfdna_yield(&mut self, v: f64) {
        self.cfdna_yield = ::std::option::Option::Some(v);
    }

    // optional double albumin = 2;

    pub fn albumin(&self) -> f64 {
        self.albumin.unwrap_or(-1.0f64)
    }

    pub fn clear_albumin(&mut self) {
        self.albumin = ::std::option::Option::None;
    }

    pub fn has_albumin(&self) -> bool {
        self.albumin.is_some()
    }

    // Param is passed by value, moved
    pub fn set_albumin(&mut self, v: f64) {
        self.albumin = ::std::option::Option::Some(v);
    }

    // optional double ldh = 3;

    pub fn ldh(&self) -> f64 {
        self.ldh.unwrap_or(-1.0f64)
    }

    pub fn clear_ldh(&mut self) {
        self.ldh = ::std::option::Option::None;
    }

    pub fn has_ldh(&self) -> bool {
        self.ldh.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ldh(&mut self, v: f64) {
        self.ldh = ::std::option::Option::Some(v);
    }

    // optional double alp = 4;

    pub fn alp(&self) -> f64 {
        self.alp.unwrap_or(-1.0f64)
    }

    pub fn clear_alp(&mut self) {
        self.alp = ::std::option::Option::None;
    }

    pub fn has_alp(&self) -> bool {
        self.alp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_alp(&mut self, v: f64) {
        self.alp = ::std::option::Option::Some(v);
    }

    // optional double psa = 5;

    pub fn psa(&self) -> f64 {
        self.psa.unwrap_or(-1.0f64)
    }

    pub fn clear_psa(&mut self) {
        self.psa = ::std::option::Option::None;
    }

    pub fn has_psa(&self) -> bool {
        self.psa.is_some()
    }

    // Param is passed by value, moved
    pub fn set_psa(&mut self, v: f64) {
        self.psa = ::std::option::Option::Some(v);
    }

    // optional int32 liver_mets = 6;

    pub fn liver_mets(&self) -> i32 {
        self.liver_mets.unwrap_or(-1i32)
    }

    pub fn clear_liver_mets(&mut self) {
        self.liver_mets = ::std::option::Option::None;
    }

    pub fn has_liver_mets(&self) -> bool {
        self.liver_mets.is_some()
    }

    // Param is passed by value, moved
    pub fn set_liver_mets(&mut self, v: i32) {
        self.liver_mets = ::std::option::Option::Some(v);
    }

    // optional int32 lung_mets = 7;

    pub fn lung_mets(&self) -> i32 {
        self.lung_mets.unwrap_or(-1i32)
    }

    pub fn clear_lung_mets(&mut self) {
        self.lung_mets = ::std::option::Option::None;
    }

    pub fn has_lung_mets(&self) -> bool {
        self.lung_mets.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lung_mets(&mut self, v: i32) {
        self.lung_mets = ::std::option::Option::Some(v);
    }

    // optional int32 ecog = 8;

    pub fn ecog(&self) -> i32 {
        self.ecog.unwrap_or(-1i32)
    }

    pub fn clear_ecog(&mut self) {
        self.ecog = ::std::option::Option::None;
    }

    pub fn has_ecog(&self) -> bool {
        self.ecog.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ecog(&mut self, v: i32) {
        self.ecog = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "cfdna_yield",
            |m: &Sample| { &m.cfdna_yield },
            |m: &mut Sample| { &mut m.cfdna_yield },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "albumin",
            |m: &Sample| { &m.albumin },
            |m: &mut Sample| { &mut m.albumin },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "ldh",
            |m: &Sample| { &m.ldh },
            |m: &mut Sample| { &mut m.ldh },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "alp",
            |m: &Sample| { &m.alp },
            |m: &mut Sample| { &mut m.alp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "psa",
            |m: &Sample| { &m.psa },
            |m: &mut Sample| { &mut m.psa },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "liver_mets",
            |m: &Sample| { &m.liver_mets },
            |m: &mut Sample| { &mut m.liver_mets },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "lung_mets",
            |m: &Sample| { &m.lung_mets },
            |m: &mut Sample| { &mut m.lung_mets },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "ecog",
            |m: &Sample| { &m.ecog },
            |m: &mut Sample| { &mut m.ecog },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Sample>(
            "Sample",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Sample {
    const NAME: &'static str = "Sample";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                9 => {
                    self.cfdna_yield = ::std::option::Option::Some(is.read_double()?);
                },
                17 => {
                    self.albumin = ::std::option::Option::Some(is.read_double()?);
                },
                25 => {
                    self.ldh = ::std::option::Option::Some(is.read_double()?);
                },
                33 => {
                    self.alp = ::std::option::Option::Some(is.read_double()?);
                },
                41 => {
                    self.psa = ::std::option::Option::Some(is.read_double()?);
                },
                48 => {
                    self.liver_mets = ::std::option::Option::Some(is.read_int32()?);
                },
                56 => {
                    self.lung_mets = ::std::option::Option::Some(is.read_int32()?);
                },
                64 => {
                    self.ecog = ::std::option::Option::Some(is.read_int32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.cfdna_yield {
            my_size += 1 + 8;
        }
        if let Some(v) = self.albumin {
            my_size += 1 + 8;
        }
        if let Some(v) = self.ldh {
            my_size += 1 + 8;
        }
        if let Some(v) = self.alp {
            my_size += 1 + 8;
        }
        if let Some(v) = self.psa {
            my_size += 1 + 8;
        }
        if let Some(v) = self.liver_mets {
            my_size += ::protobuf::rt::int32_size(6, v);
        }
        if let Some(v) = self.lung_mets {
            my_size += ::protobuf::rt::int32_size(7, v);
        }
        if let Some(v) = self.ecog {
            my_size += ::protobuf::rt::int32_size(8, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.cfdna_yield {
            os.write_double(1, v)?;
        }
        if let Some(v) = self.albumin {
            os.write_double(2, v)?;
        }
        if let Some(v) = self.ldh {
            os.write_double(3, v)?;
        }
        if let Some(v) = self.alp {
            os.write_double(4, v)?;
        }
        if let Some(v) = self.psa {
            os.write_double(5, v)?;
        }
        if let Some(v) = self.liver_mets {
            os.write_int32(6, v)?;
        }
        if let Some(v) = self.lung_mets {
            os.write_int32(7, v)?;
        }
        if let Some(v) = self.ecog {
            os.write_int32(8, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Sample {
        Sample::new()
    }

    fn clear(&mut self) {
        self.cfdna_yield = ::std::option::Option::None;
        self.albumin = ::std::option::Option::None;
        self.ldh = ::std::option::Option::None;
        self.alp = ::std::option::Option::None;
        self.psa = ::std::option::Option::None;
        self.liver_mets = ::std::option::Option::None;
        self.lung_mets = ::std::option::Option::None;
        self.ecog = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Sample {
        static instance: Sample = Sample {
            cfdna_yield: ::std::option::Option::None,
            albumin: ::std::option::Option::None,
            ldh: ::std::option::Option::None,
            alp: ::std::option::Option::None,
            psa: ::std::option::Option::None,
            liver_mets: ::std::option::Option::None,
            lung_mets: ::std::option::Option::None,
            ecog: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Sample {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Sample").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Sample {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Sample {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:samples.Classification)
pub struct Classification {
    // message fields
    // @@protoc_insertion_point(field:samples.Classification.label)
    pub label: ::std::option::Option<bool>,
    // special fields
    // @@protoc_insertion_point(special_field:samples.Classification.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Classification {
    fn default() -> &'a Classification {
        <Classification as ::protobuf::Message>::default_instance()
    }
}

impl Classification {
    pub fn new() -> Classification {
        ::std::default::Default::default()
    }

    // optional bool label = 1;

    pub fn label(&self) -> bool {
        self.label.unwrap_or(false)
    }

    pub fn clear_label(&mut self) {
        self.label = ::std::option::Option::None;
    }

    pub fn has_label(&self) -> bool {
        self.label.is_some()
    }

    // Param is passed by value, moved
    pub fn set_label(&mut self, v: bool) {
        self.label = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "label",
            |m: &Classification| { &m.label },
            |m: &mut Classification| { &mut m.label },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Classification>(
            "Classification",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Classification {
    const NAME: &'static str = "Classification";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.label = ::std::option::Option::Some(is.read_bool()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.label {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.label {
            os.write_bool(1, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Classification {
        Classification::new()
    }

    fn clear(&mut self) {
        self.label = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Classification {
        static instance: Classification = Classification {
            label: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Classification {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Classification").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Classification {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Classification {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rsamples.proto\x12\x07samples\"\xe9\x01\n\x06Sample\x12#\n\x0bcfdna_y\
    ield\x18\x01\x20\x01(\x01:\x02-1R\ncfdnaYield\x12\x1c\n\x07albumin\x18\
    \x02\x20\x01(\x01:\x02-1R\x07albumin\x12\x14\n\x03ldh\x18\x03\x20\x01(\
    \x01:\x02-1R\x03ldh\x12\x14\n\x03alp\x18\x04\x20\x01(\x01:\x02-1R\x03alp\
    \x12\x14\n\x03psa\x18\x05\x20\x01(\x01:\x02-1R\x03psa\x12!\n\nliver_mets\
    \x18\x06\x20\x01(\x05:\x02-1R\tliverMets\x12\x1f\n\tlung_mets\x18\x07\
    \x20\x01(\x05:\x02-1R\x08lungMets\x12\x16\n\x04ecog\x18\x08\x20\x01(\x05\
    :\x02-1R\x04ecog\"&\n\x0eClassification\x12\x14\n\x05label\x18\x01\x20\
    \x01(\x08R\x05label\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(Sample::generated_message_descriptor_data());
            messages.push(Classification::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
